data_path:
  RAW_DIR_PATH: "artifacts/raw_dir"
  RAW_FILE_NAME: "hotel_reservation_file.csv"
cat_numerical_feature:
  cat_cols: ['type_of_meal_plan','required_car_parking_space','room_type_reserved','market_segment_type', 'repeated_guest','booking_status']
  num_cols: ['no_of_adults', 'no_of_children', 'no_of_weekend_nights',
              'no_of_week_nights','lead_time', 'arrival_year', 'arrival_month',
              'arrival_date','no_of_previous_cancellations', 'no_of_previous_bookings_not_canceled',
              'avg_price_per_room', 'no_of_special_requests']
model_saving_path:
  model_dir_path: "artifacts/model_dir"
  model_file_name: "model.pkl"              
